# Generated by Django 4.2.6 on 2023-10-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=50)),
                ('mission_type', models.CharField(max_length=50)),
                ('mission_duration', models.CharField(max_length=20)),
                ('mission_launch', models.CharField(max_length=20)),
            ],
        ),
    ]
