# Generated by Django 4.2.6 on 2023-10-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
